# -*- coding: utf-8 -*-
"""2nd yr python cia-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBuY4YZx_Kqz0TgYH0MYJvzm88ecWKhr
"""

#Expense Tracker for each month of a year
print("Expense Tracker")
print("Purpose : To track your expenditure for each month and take note of each of your expenses and give a visual representation.")
print()
print()

import matplotlib.pyplot as plt
def track_expenses():
    try:
        total_amt = 0
        amt_list = []

        # First we take a budget
        budget = int(input("Enter a budget: "))
        # You can choose the number of months for which you want to track your expenses
        no_of_months = int(input("Enter number of months for which you want to track your budget : "))

        i=1
        list_of_expenses = [
            "Rent", "Food", "Stationary", "Traveling Expense", "Shopping",
            "Entertainment", "Medical", "Personal Care", "Miscellaneous Expenses"
        ]

        for _ in range(no_of_months):
            print()
            print("Month ",i," : ")
            for expense in list_of_expenses:
                print(expense)
                while True:
                    try:
                        amount = int(input("Enter amount spent: "))
                        if amount < 0:
                            raise ValueError("Amount spent cannot be negative.")
                        break
                    except ValueError as e:
                        print("Invalid input. Please enter a valid positive integer amount.")
                        print(e)
                        print()

                amt_list.append(amount)
                total_amt += amount
                print()

            print("The total amount spent in the month is", total_amt)
            if total_amt > budget:
                print("Need to control spending")
            else:
                print("Budget is maintained")

            plt.figure(figsize=(10, 6))
            plt.plot(amt_list)
            plt.title('Your expense chart')
            plt.xlabel('Expenses')
            plt.ylabel('Amount')
            plt.show()
            print()
            i = i+1

    except Exception as e:
        print("An error occurred:")
        print(e)

track_expenses()